---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: floki
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy nginx app 
      community.kubernetes.k8s:
        src: /mnt/c/Users/ahmed/IdeaProjects/learn-ansible/nginx.yaml
        state: present
        namespace: my-app
