---
- name: Install java and net-tools
  hosts: nexus_server
  become: yes
  tasks:
    - name: Update apt repo and cache
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install Java 8
      ansible.builtin.apt: name=openjdk-8-jre-headless      

    - name: Install net-tools
      ansible.builtin.apt: 
            name: net-tools  

- name: Download and unpack Nexus installer
  hosts: nexus_server
  tasks: 
    - name: Check nexus folder stats
      ansible.builtin.stat:
        path: /home/ubuntu/nexus
      register: stat_result  
    - debug: msg={{stat_result.stat.exists}}

    - name: Download Nexus
      ansible.builtin.get_url: 
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /home/ubuntu
      register: download_result  
    
    - name: Untar nexus installer
      ansible.builtin.unarchive:
        src: "{{download_result.dest}}"
        dest: /home/ubuntu
        remote_src: yes   
      when: not stat_result.stat.exists

    - name: Find nexus folder
      ansible.builtin.find: 
        paths: /home/ubuntu
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    
    - name: Rename nexus folder
      ansible.builtin.shell: mv {{find_result.files[0].path}} /home/ubuntu/nexus
      when: not stat_result.stat.exists 
